service:
  name: ${env:SERVICE_NAME}
plugins:
  - serverless-pseudo-parameters
  - serverless-dotenv-plugin
custom:
  dotenv:
    path: ./.env
provider:
  name: aws
  runtime: nodejs6.10
  stage: ${env:STAGE}
  region: ${env:REGION}
  memorySize: 128
  timeout: 16
  # environment: ${file(./env.yml):${self:provider.stage}}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lex:*"
      Resource: "arn:aws:lex:${self:provider.region}:#{AWS::AccountId}:bot:OrderFlowers:order_rose"
    - Effect: "Allow"
      Action:
        - "lambda:*"
      Resource: "arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-processMessage"
package:
  exclude:
    - '*.js'
    - '*.yml'
  include:
    - handler.js
  excludeDevDependencies: false
functions:
  handleMessage:
    handler: handler.handleMessage
    events:
      - http:
          path: messages/handle
          method: post
  processMessage: # invoked via aws SDK
    handler: handler.processMessage
